# Generated by Django 5.2.17 on 2026-09-19 14:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('url', models.CharField(max_length=512)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('artwork_key', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=16)),
                ('sort_order', models.IntegerField(default=0)),
                ('name_en', models.CharField(max_length=160)),
                ('name_ar', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('currency', models.CharField(max_length=8)),
                ('locked', models.BooleanField(default=True)),
                ('name_en', models.CharField(max_length=160)),
                ('name_ar', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('href', models.CharField(blank=True, max_length=255)),
                ('artwork_key', models.CharField(blank=True, max_length=64)),
                ('artwork_url', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=16)),
                ('sort_order', models.IntegerField(default=0)),
                ('name_en', models.CharField(max_length=160)),
                ('name_ar', models.CharField(blank=True, max_length=160)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('GIFT_CARD', 'Gift card'), ('WALLET', 'Wallet'), ('GAME_CURRENCY', 'Game currency'), ('SUBSCRIPTION', 'Subscription'), ('DIRECT_TOPUP', 'Direct top-up'), ('DIGITAL_CODE', 'Digital code')], max_length=32)),
                ('fulfillment_type', models.CharField(choices=[('CODE', 'Code'), ('DIRECT_TOPUP', 'Direct top-up')], max_length=32)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('SUPPLIER', 'Supplier')], default='MANUAL', max_length=16)),
                ('brand', models.CharField(max_length=120)),
                ('artwork_key', models.CharField(max_length=64)),
                ('account_currency', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('featured', models.BooleanField(default=False)),
                ('bestseller', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('refundable', models.BooleanField(default=False)),
                ('region_warning_en', models.TextField(blank=True)),
                ('region_warning_ar', models.TextField(blank=True)),
                ('delivery_estimate_en', models.CharField(blank=True, max_length=255)),
                ('delivery_estimate_ar', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('badges', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('short_description_en', models.TextField(blank=True)),
                ('short_description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('instructions_en', models.TextField(blank=True)),
                ('instructions_ar', models.TextField(blank=True)),
                ('how_to_use_en', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('how_to_use_ar', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('region_restrictions_en', models.TextField(blank=True)),
                ('region_restrictions_ar', models.TextField(blank=True)),
                ('refund_policy_en', models.TextField(blank=True)),
                ('refund_policy_ar', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.platform')),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=120, unique=True)),
                ('denomination', models.DecimalField(decimal_places=2, max_digits=12)),
                ('package_value', models.CharField(max_length=64)),
                ('package_currency', models.CharField(max_length=8)),
                ('cost_fils', models.IntegerField(default=0)),
                ('price_fils', models.IntegerField()),
                ('compare_at_price_fils', models.IntegerField(blank=True, null=True)),
                ('stock_status', models.CharField(choices=[('IN_STOCK', 'In stock'), ('OUT_OF_STOCK', 'Out of stock'), ('UNKNOWN', 'Unknown')], default='IN_STOCK', max_length=16)),
                ('min_quantity', models.IntegerField(default=1)),
                ('max_quantity', models.IntegerField(default=5)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('name_en', models.CharField(max_length=160)),
                ('name_ar', models.CharField(blank=True, max_length=160)),
                ('external_id', models.CharField(blank=True, help_text='Storefront denomination id', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='catalog.region')),
            ],
            options={
                'ordering': ['sort_order', 'price_fils'],
            },
        ),
        migrations.CreateModel(
            name='ProductFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('EMAIL', 'Email'), ('TEL', 'Tel'), ('SELECT', 'Select')], default='TEXT', max_length=16)),
                ('required', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('label_en', models.CharField(max_length=120)),
                ('label_ar', models.CharField(blank=True, max_length=120)),
                ('placeholder_en', models.CharField(blank=True, max_length=160)),
                ('placeholder_ar', models.CharField(blank=True, max_length=160)),
                ('help_text_en', models.CharField(blank=True, max_length=255)),
                ('help_text_ar', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'key'],
                'unique_together': {('product', 'key')},
            },
        ),
    ]
