# Generated by Django 5.2.17 on 2026-09-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=255)),
                ('kicker', models.CharField(blank=True, max_length=120)),
                ('tone', models.CharField(default='gold', max_length=32)),
                ('placement', models.CharField(choices=[('HOME', 'Home'), ('SHOP', 'Shop'), ('CATEGORY', 'Category'), ('PROMO', 'Promo')], default='HOME', max_length=16)),
                ('desktop_image', models.CharField(blank=True, max_length=512)),
                ('mobile_image', models.CharField(blank=True, max_length=512)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=255)),
                ('subtitle_ar', models.CharField(blank=True, max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('body_en', models.TextField()),
                ('body_ar', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=255)),
                ('question_ar', models.CharField(blank=True, max_length=255)),
                ('answer_en', models.TextField()),
                ('answer_ar', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order'],
            },
        ),
    ]
