# Generated by Django 5.2.17 on 2026-09-19 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='storage_path',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
