# Generated by Django 5.2.17 on 2026-09-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='coupon',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalcode',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('DELIVERED', 'Delivered'), ('UNAVAILABLE', 'Unavailable')], default='DELIVERED', max_length=16),
        ),
        migrations.AddField(
            model_name='digitalcode',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_codes', to='catalog.productvariant'),
        ),
        migrations.AlterField(
            model_name='digitalcode',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='commerce.orderitem'),
        ),
    ]
