# Generated by Django 5.2.17 on 2026-09-19 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('commerce', '0002_admin_api_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcode',
            name='code_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='digitalcode',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='digitalcode',
            name='source',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('CSV_IMPORT', 'CSV / spreadsheet import'), ('ONEEPIN', 'OneEpin'), ('CHECKOUT_DEMO', 'Checkout demo')], default='MANUAL', max_length=32),
        ),
        migrations.CreateModel(
            name='CodeImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('SIMPLE', 'Simple'), ('ADVANCED', 'Advanced')], default='SIMPLE', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('duplicate_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('error_report', models.JSONField(blank=True, default=list)),
                ('preview_rows', models.JSONField(blank=True, default=list)),
                ('pending_file_path', models.CharField(blank=True, max_length=512)),
                ('file_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_import_batches', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_import_batches', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='digitalcode',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes', to='commerce.codeimportbatch'),
        ),
    ]
